Feat/luxury25
real-tough-guys/luxury-shopping-mall pull request #27
Opened 2021-03-28 10:04 UTC by jhj960918

test/java/service/ProductServiceTest
save 메소드 오류 Line 64

2021-03-28 15:50 UTC, rlatls1997 approved these changes
확인했습니다.

2021-03-29 11:28 UTC, DunDung requested changes
형준님 고생하셨습니다 👍 
1차적으로 눈에 보이는 것만 슥슥 리뷰해봤어요!
제가 리뷰해드린 내용들 공부해보시고 코드에 적용해보시면 좋을 것 같슴니다😊
더 말씀드리고 싶은 내용이 많은데 천천히 해보죠..
수정 반영하시면 한 번 더 리뷰요청 해주세요!

추가적으로 코드 리뷰 드린 내용 외에 말씀드리고 싶은 건
커밋 단위를 기능 단위로하고 커밋메세지를 좀 더 상세하고 자세히 적어보아요!
요청 받은 데이터를 검증하는 로직을 Spring validate를 사용해서 추가해보아요!
Spring validation은 관련 좋은 글 첨부해드릴게요!
[Spring Boot에서 DTO 검증하기](https://woowacourse.github.io/javable/post/2020-09-20-validation-in-spring-boot/)

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/ProductController.java
> +@RequestMapping("/api/product")
리소스는 복수로 해주는게 맞다고 해요product -> products
아래 이미지 내용 읽어보세요!
![image](https://user-images.githubusercontent.com/33235211/112823119-d1ee2600-90c3-11eb-8412-9316b64c0e53.png)
 더 자세한 내용은 시간되실 때 [MS API 디자인 지침](https://docs.microsoft.com/ko-kr/azure/architecture/best-practices/api-design) 읽어보시면 좋을 듯!

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/ProductController.java
> +    ProductService productService;
DI를 @Autowired를 사용한 필드 주입으로 하셨는데 특별한 이유가 없다면
DI를 하는 3가지 방법을 공부해보시고 스프링 공식 레퍼런스에서는 왜 생성자 DI를 권장하는지 한 번 공부해보세요:)
공부하실 때 도움이 될만한 좋은 글 첨부합니다!
[왜 Constructor Injection을 사용해야 하는가?](https://woowacourse.github.io/javable/post/2020-07-18-di-constuctor-injection/)

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/ProductController.java
> +    @GetMapping("")
```suggestion
    @GetMapping
```
빈 문자열은 없어도 상관없습니다!

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/ProductController.java
> +    }
컨트롤러에서 ResponseEntity 를 반환하는 것은 어떨까요?
ResponseEntity를 공부해보시고 ResponseEntity를 반환했을 때 어떤 장점이 있는지 공부해보아요!
[이 글](https://doublesprogramming.tistory.com/204)의 ResponseEntity 부분을 보면 도움이 될거예요 :)

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/ProductController.java
> +
불필요한 공백이 가독성을 저하시킵니다! 
이 클래스 33번째 line을 포함해서 전체적으로 확인해주세용

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/dto/ProductDto.java
> +public class ProductDto {
클래스 네이밍이 의도가 명확하지 않다고 생각해요.
어떤 상황에서 쓰이는 DTO인지 확 와닿지가 않습니다!
Request를 받을 때 사용한다면 ProductRequestDto 처럼 명확한 이름은 어떨까요?

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/dto/ProductDto.java
> +    private String productCategory;
클래스 이름에서 명확하게 어떤 역할을 하는 객체인지 표현해준다면
인스턴스 변수 이름이 조금 간단해질 수 있을 것 같아요!
```suggestion
    private String name;
    private String price;
    private String category;
```

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/dto/ProductDto.java
> +    private String imageurl1;
변수이름에 숫자는 지양하는 편이 좋다고 생각해요!
그리고 imageUrl은 카멜케이스를 적용해야 하는 두개의 단어가 아닌가요? 여쭤보는겁니다!

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/dto/ProductDto.java
> +        ProductEntity boardEntity = ProductEntity.builder()
toEntity라는 메서드 네임이 의도가 명확하지 않다고 생각해요. 
엔티티로 변환하는 것은 알겠는데 어떤 엔티티인지가 헷갈릴 수 있다고 생각합니다.
하나의 dto에서 여러 엔티티로 변환하는 경우도 있을 수 있고 말이죠!
이런 경우에는 toProductEntity 와 같은 네이밍을 해주는게 더 명확하지 않을까요?

그리고 return할 ProductEntity 객체의 이름이 boardEntity인것도 명확하지 않습니다!
단지 엔티티로의 변환이라면 바로 return을 해주시거나
 다른 의미를 내포하고 싶다면 좀 더 명확한 네이밍으로 수정하는건 어떨까요?

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/service/ProductService.java
> +    private ProductRepository productRepository;
final 키워드를 붙여서 인스턴스 변수를 생성하는 것을 고려해보세요!
final 키워드의 기능과 불변 객체의 장점, final 키워드를 어디까지 붙이는게 좋을지(메서드 매개변수, 인스턴스 변수 등)
등등 불변 객체와 관련된 공부를 해보시는 걸 추천합니다!

이런 부분에 많은 의견은 있는데  정답은 없는거라 공부해보시고
 형준님이 맞다고 생각하는 의견이나 생각을 찾아보세요!

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/service/ProductService.java
> +    }
조회만 해오는 메서드에서 `@Transactional`이 필요할까요!? 
`@Transactional`은 최소한으로 달아주는 것이 좋은데 왜일까요??! 
스프링 트랜잭션 관련 공부를 해보시길 추천합니다!

---

Optional에서 get 메서드만을 사용해서 데이터를 가져오는 것은 지양합니다. 왜일까요??
Optional은 비용이 비싸서 모르고 쓰면 성능 저하로 이어질 수 있기 때문에 
관련된 공부를 해보시길 추천합니다!

2021-03-29 11:28 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/service/ProductService.java
> +    }
Entity 객체를 Dto로 변환해주는게 Service의 역할이 맞을까요?!?
Service는 최소한으로 만들어주는게 객체지향적 관점에서 좋습니다!
관련해서는 이 글 [빈약한 도메인 모델](https://m.blog.naver.com/PostView.nhn?blogId=muchine98&logNo=220304821784&proxyReferer=https:%2F%2Fwww.google.com%2F)을 읽어보면 좋은데
지금은 이해가 잘 되지 않을거에요. 일단 읽어만 보세요!
결론적으로 Entity -> Dto의 변환은 따로 그 역할을 하는 객체가 있으면 좋다고 생각합니다.
지금은 ProductDto가 요청과 응답을 처리하는? 역할을 하고있는데
그 책임을 분리하는게 좋다고 생각해요.
웹 서비스에서 굉장히 자주 바뀌는 부분이 요청 데이터랑 응답 데이터인데
그 둘이 한 곳에 있다면 변경에 유연하게 대처를 못할 거예요.
게다가 findById를 했을 때 저 Dto에 있는 인스턴스 변수가 모두 필요한 데이터인지도 확인을 해봐야 합니다!
DTO를 반환할 땐 꼭 필요한 데이터만 리턴해줘야 DTO를 사용하는 의미가 있을거예요.
더해서 product를 등록하는 요청을 productDto를 통해 받을때 요청받은 데이터를 검증도 해줘야하는데
한 곳에 있으면 불가능하겠죠?!?!?
제 생각엔 productDto 를 productRequest와 productResponse로 분리하고
productResponse에서 위 메서드와 같은 ProductEntity를 받아서 객체를 생성하는 책임을 가져간다면
더 책임과 역할이 분명해질것 같아요!
이 부분은 객체지향이 익숙하지 않으면 조금 어려울 수 있어요 ㅠㅠ

2021-03-29 11:28 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/service/ProductServiceTest.java
> +class ProductServiceTest {
테스트 관련해서도 드릴 말씀이 많은데
이번에는 리뷰 내용이 많으니 수정 반영하시면 테스트는 그때 다시 리뷰해드릴게요!

2021-03-29 13:17 UTC, jhj960918 commented on src/test/java/com/skhu/luxuryshop/service/ProductServiceTest.java
> +class ProductServiceTest {
정말 고생하셨습니다!! 수정 반영 진행해 볼게요!!

2021-03-29 13:33 UTC, DunDung requested changes
신혁님꺼 리뷰하다가 하나 추가해용~

2021-03-29 13:33 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/entity/ProductEntity.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
왜 access level을 PROTECTED로 했는지 설명할 수 있어야합니다!

2021-04-05 10:59 UTC, DunDung requested changes
형준님 고생하셨슴니다 👍 
이번 주 바쁘셨나봐요.. 아직 전에 리뷰가 반영되지 않은 부분이 많은것 같아요.
한 번더 전체적으로 리뷰 반영이 됐나 확인해주세요!
프로덕트 코드 완성이 되면 테스트 코드 꼼꼼히 봐드릴게요!

2021-04-05 10:59 UTC, DunDung commented on build.gradle
> +    implementation 'junit:junit:4.12'
junit5를 사용하기로 했는데 이 의존성을 추가하신거 보니까 어떤 에러가 있었나봐요. 
제가 예상하는 에러가 맞다면 아마 이 junt4 의존성 지우고 

원래있던 
```gradle
testImplementation 'org.springframework.boot:spring-boot-starter-test'
```
을 아래처럼 바꿔주면 아마 해결될지도 몰라요.
```gradle
testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
}
```
spring-boot-starter-test'에서는 junit4를 default로 사용해서 위 코드처럼 exclude 해줘야 junit5를 사용할 수 있씁니다!

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/LuxuryshopApplication.java
> +}
불필요한 줄바꿈이 조금 있네요 :) 코드 전체적으로 확인 한 번더 해주세용

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +    }
lombok을 사용하는 김에 이 부분을 @RequiredArgsConstructor 로 대체해보는 것은 어떨까요.
물론 무조건적으로 사용하는 게 좋은 건 아닙니다! 고려해볼 수 있다~~ 라는 것 입니다.

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +    public ResponseEntity getProducts() {
ResponseEntity를 반환하는 모든 곳에서 ExceptionHandler에서 그랬듯이 제네릭을 사용해주는 건 어떨까요!?
제네릭을 사용하여 ResponseEntity를 반환하도록 수정하는 것은 사실 쉬운 작업이지만
제네릭이 저희같은 초보 개발자들은 구현할 일이 별로 없어서 가장 애매하게 아는 부분일 수 있거든요.
구현은 안하지만 매번 사용은하는 제네릭을 왜 쓰는지, 장점은 무엇인지 알고 써야하니까
제네릭에 대해서 한 번 더 공부해보는 걸 추천해요. 은근 파보면 깊은 내용이 많슴니다!
부족하지만 제가 쓴 글 첨부해드려용 ㅎㅎㅎ 한 번 가볍게 읽어보세용.
[자바 제네릭 기초](https://dundung.tistory.com/269)
[자바 제네릭 조금 심화](https://dundung.tistory.com/274)

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +    }
이 부분만 ResponseEntity를 안 쓴 이유가 있을까요?!?
ResponseEntity 사용 이유를 생각해보면 이 메서드에서도 안 쓸 이유는 없어보임니다!

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +        return ResponseEntity.badRequest().body(errors);
개발자들도 exception의 내용을 알아야하기 때문에 log를 찍어줄 필요가 있어보여요.

그리고 사용자에게 어떤 내용의 exception이 발생했는지 정확히 알려주어야 좋습니다!
프론트는 서버에서 온 이 에러 내용을 받아서 사용자에게 보여줘야하는데
지금 코드로는 사용자 입장에서는 뭘 잘못 입력했는지 알 수가 없기때문입니다. 
exception을 throw할 때 아무 메세지도 담고있지 않아서요! 프론트에서 처리를 잘할 수 있고, 사용자가 쉽게 알아들을 수 있게 작성해주어야 좋습니다!

validation으로 검증할때
```java 
@Email(message = "이메일 형식이 맞지 않습니다.")
```
이런식으로 메세지를 구체적으로 보내주면 좋을 것 같습니다.

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/dto/ProductRequestDto.java
> +public class ProductRequestDto {
request DTO에서 validation 검증을 해주고있지 않네요! 아직 못하신거겠죵??

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/dto/ProductResponseDto.java
> +    }
이 부분도 아직 static factory method로 수정 못하신거겠죠!?!??
static factory method 관련 좋은글 첨부해드림니다 :)
[정적 팩토리 메서드(Static Factory Method)는 왜 사용할까?](https://woowacourse.github.io/javable/post/2020-05-26-static-factory-method/)

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/service/ProductService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 상품이 없습니다. id=" + id));
orElseThrow 👍 

여기서 반환한 IAE도 ExceptionHandler가 필요하겠네요.
여기서처럼 validation으로 검증할 때도 예외메세지를 구체적으로 작성해주세요!

2021-04-05 10:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/entity/ProductEntity.java
> +    private String imageurl1;
상품에 이런 인스턴스변수들 전부 길이만 제한하면 되는걸까요?!?!
상품 이름이나 가격은 비어있으면 안될 것 같긴해요!
가격도 String이면 숫자가 아닌 데이터도 들어올 수 있겠네요.
이런 것들을 좀 더 세심하게 생각하셔서 다시 한 번 적용해주세요!

2021-04-05 12:07 UTC, DunDung requested changes

2021-04-05 12:07 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/entity/ProductEntity.java
> +    private long id;
Entity의 id는 보통 primitive type이 wrapper class를 사용합니다! 
그래서 long이 아닌 Long을 사용하는게 더 맞겠죠! 왜일까요!?!?
생각해보시고 [이 글](https://hanga-evernote.com/106)을 참고해보세요!
내용이 이해되지 않으시면 더 검색해보시길 추천드려요!

2021-04-09 11:46 UTC, jhj960918 reviewed
gradle에 의존성을 추가하고 여러 방법으로 Test를 진행해 봤는데 Buid Faild Error가 뜨네요 
일단은 한 부분까지 Push 했습니다!!

2021-04-12 12:30 UTC, DunDung requested changes
형준님 고생하셨습니다 ~ 
테스트 코드 추가가 필요해보여요 ㅠ
제 리뷰가 정답이 아니니까 의문이 생기거나 더 맞는 방법이 있는 것 같으면 꼭 말해주세요.
이번 리뷰도 열심히 반영해보아요!!

2021-04-12 12:30 UTC, DunDung commented on build.gradle
> +    implementation 'junit:junit:4.12'
```suggestion
```
요거 지워도 제 노트북으로 형준님 브랜치에서 테스트 잘 돌아갑니다!
Buid Faild Error가 어떻게 뜨던가요? 다시 한 번 확인해보세요!

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controllerAdvice/ProductExceptionControllerAdvice.java
> +    }
```suggestion
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<String> methodArgumentNotValidException(MethodArgumentNotValidException e) {
        log.error( e.getMessage(), e );
        return new ResponseEntity( e.getMessage(), HttpStatus.BAD_REQUEST );
    }
```

ResponseEntity에 HttpStatus를 인자로 보내고있으니 `@ResponseStatus`는 필요 없어 보입니다 :)

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controllerAdvice/ProductExceptionControllerAdvice.java
> +    }
ResponseEntity로 HttpStatus를 보내주고있어서 `@ResponseStatus`는 필요 없어 보입니다 :)
그리고 예상치못한 에러를 잡아주는 용도로 Exception을 잡아주는 메서드도 필요해 보여요.
Exception을 잡아주는 메서드에는 다른 메서드들처럼 ResponseEntity에 
e.getMessage()를 응답하면 보안상의 이유로 문제가 생길수도 있으니 "예상치못한 에러" 이 정도만 
보내주면 될 것 같아요. 이렇게 예상치못한 에러는 어떤 HttpStatus를 응답하는게 적절할까요?
공부해보시고 추가해보세요 !

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +    }
POST 매핑으로 새로운 데이터를 저장했을 경우에는 200 OK도 가능하지만 
보통 201 created 상태 코드를 씁니다!
그리고 새로 생성 된 리소스를 반환받을 수 있는 uri를 header에 넣어줍니다!

응답한 데이터를 명확하게 표현하기 위한 ststus code 중에하나인 201 code도 공부해보길 추천해요!

productService.save를 조금 수정하고 이런식으로 수정하면 될 거예요.
```suggestion
        return ResponseEntity.created(URI.create("/" + savedProduct.getId())).build();
```

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +    }
왜냐면 HttpStatus.OK를 보내주고 있기때문에 상품 업데이트 성공했다는 메세지는 응답할 필요가 없어보입니다. :)
업데이트시 필요한 데이터가 있다면 그걸 보내주면 되고 없다면 아무것도 안보내줘도 됩니다!
```suggestion
    @PutMapping("/{id}")
    public ResponseEntity<Long> updateProduct(@PathVariable Long id, @RequestBody @Valid ProductRequestDto productRequestDto) {
        productService.update(id, productRequestDto);
        return ResponseEntity.ok().build();
    }
```

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +    }
post 매핑으로 새로운 데이터를 만들었을땐 201 created를 사용하듯이
delete 매핑으로 삭제에 성공했을 때 적절한 status code는 뭘까요?!?
공부해보시고 적절한 status code를 return하도록 수정해보아요.

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/dto/ProductRequestDto.java
> +    private String imageurl;
카멜케이스로 하는게 맞지 않나요!??? 
```suggestion
    private String imageUrl;
```
그리고 그때 카톡으로 말했듯이 다중 이미지를 할 거라면 일급 컬렉션 객체로 포장해보아요.

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/entity/ProductEntity.java
> +    private String imageurl;
request dto는 검증이 에러메시지와 함께 String 객체에서는 NotBlank로 잘 수정되어있었는데
이부분은 적용이 안돼있네요! 오히려 더 철저하게 검증을 해줘야하는 쪽은 Entity랍니다!

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/entity/ProductEntity.java
> +    }
ProductRequestDto를 파라미터로 받아서 update를 해주는건 조금 어색해보여요!
만약 상품 관련 요청이 여러개 생겨서 RequestDTO가 여러개 생긴다면 
그때마다 연관된 update를 여러개 추가해줘야 하지 않을까요?
이 부분은 확장에 용이하게 해주기 위해 ProductEntity를 파라미터로 받는게 맞는 것 같아요!
그리고 이 부분도 테스트 해줘야 할 것 같네요!

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/service/ProductService.java
> +        return productEntity.getId();
controller에서는 id를 사용하고 있지 않는데 service에서는 id를 return하고 있네요!
위에서 말씀드린 ProductEntity.update를 수정하면서 이 부분이 수정되겠지만
업데이트하려는 상품이 존재하는지 확인하기 위해 findById.orElseThrow를 해보는 것보다는
jpa의 existBy{field name}를 활용하는게 의미전달에 더 좋았을 것 같아요!

2021-04-12 12:30 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/service/ProductService.java
> +        productRepository.deleteById(id);
이 부분도 마찬가지로 exist를 활용하면 좋겠네요!

2021-04-12 12:30 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/product/repository/ProductRepositoryTest.java
> +    }
```suggestion
    @BeforeEach
    void setUp() {
        product = new ProductRequestDto("서비스Test", "서비스 컨텐트 테스트", 900, "아우터", "www.asd");
    }

    @AfterEach
    public void tearDown() {
        productRepository.deleteAll();
    }
```
setup 카멜케이스 적용이랑 @After은 junit5부터 @AfterEach로 사용하구 메서드명 컨벤션은 tearDown입니다.
그리고 불필요한 디버깅로그는 찍지 않는게 좋습니다!

2021-04-12 12:30 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/product/repository/ProductRepositoryTest.java
> +        assertTrue(productEntity.getContent().equals(product.getContent()));
repository 같은 경우에는 카톡으로도 말씀드렸듯이 jpa에서 제공하는 기능으로 신뢰성이 있기때문에
테스트하지 않아도 괜찮아요!
테스트 내용을 검증 할때 AssertJ를 사용해보시는 걸 고려해보세요!
많은 사람들과 기업에서 검증을 할때는 가독성이 좋고 제공하는 기능이 많은 AssertJ를 사용합니다!

2021-04-12 12:30 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/product/service/ProductServiceTest.java
> +class ProductServiceTest {
테스트 잘 작성하셨는데
Service에서 본인이 작성한 코드는 전부 테스트해주는게 원칙이에요!
findAll, update, findById 등등 그리고 예상한 Exception이 발생하는 case까지 테스트하는게 좋아보여요!
추가적으로 controller 테스트까지는 작성해보시는게 좋아보입니다!

2021-04-22 13:57 UTC, DunDung approved these changes
고생하셨슴다 💯 
테스트 코드 꼼꼼히 잘 작성하셨네요!
아직 반영안된 부분들 체크해드렸으니 그 부분들 반영하시면
merge해주세요!!

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +    public ResponseEntity getProducts() {
이거는 아직 반영이 안됐네요 ㅠㅠㅠ 전체적으로 제네릭 사용하고있는지 체크해주세용

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/controller/ProductController.java
> +        return ResponseEntity.ok().build();
deleteMapping으로 삭제했을 땐 보통 HttpStatus 204 noContent 많이 사용함니당.

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/dto/ProductRequestDto.java
> +    private String imageurl;
여기도 반영이 안돼있습니다~~~

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/dto/ProductRequestDto.java
> +
여기도 불필요한 줄바꿈 공백이 보이네요!

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/dto/ProductResponseDto.java
> +    private long id;
```suggestion
    private Long id;
```

id를 Long으로 했을 때 장점 저번에 리뷰달아드린거 기억하시죠! 
그거 다시 봐보시면 좋을 듯해요!  DTO에도 적용되는 장점이 있슴다!

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/entity/ProductEntity.java
> +    private String imageurl;
여기도 반영이 안돼있네요~~

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/entity/ProductEntity.java
> +
불필요한 줄바꿈 공백이 남아있습니다~~

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/entity/ProductEntity.java
> +    }
이 부분도 반영이 안돼있네요~~

2021-04-22 13:57 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/product/controller/ProductControllerTest.java
> +                , product.getCategory(), product.getImageurl());
![image](https://user-images.githubusercontent.com/33235211/115397594-3b73d700-a221-11eb-88f1-4123c1c59793.png)

줄바꿈 허용 위치도 컨벤션이 있슴니다! 별게다있죠??

```suggestion
        ProductResponseDto productResponse = new ProductResponseDto(1L, product.getName(), product.getContent(), product.getPrice(),
                product.getCategory(), product.getImageurl());
```

2021-04-22 13:57 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/product/dto/ProductResponseDto.java
> +    private String imageurl;
여기도 변수명 카멜케이스로 해주세영

2021-04-22 13:57 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/product/controller/ProductControllerTest.java
> +        assertThat(location).isEqualTo("/" + productResponse.getId());
👍

2021-04-25 11:05 UTC, merged