feat : User Create 구현
real-tough-guys/luxury-shopping-mall pull request #28
Opened 2021-03-28 15:46 UTC by rlatls1997

회원정보 create 구현입니다.

프론트 파일 수정내역은 aws올릴때 버튼이랑 링크 추가한 것 때문에 그렇습니다.
@RestController 방식은 제가 잘 몰라서 형준님꺼 보고 대충 따라했습니다 ㅠㅠ

수정해야할 부분 있으면 알려주세요!

2021-03-29 14:36 UTC, DunDung requested changes
신혁님 정말 고생하셨슴니다 💯 
처음인 부분들도 많아서 많이 힘드셨죠ㅠㅠ
형준님과 마찬가지로 1차적으로는 눈에 보이는 것만 슥슥 리뷰해봤어요.
수정 반영하시면 천천히 더 자세히 리뷰해볼게요!

코드 리뷰 드린 내용 외에 말씀드리고 싶은 건
커밋 단위를 기능 단위로하고 커밋메세지를 좀 더 상세하고 자세히 적어보아요!
그리고 `@Controller`랑 `@RestController`랑 어떤 차이점이 있는지도 공부해보아요!

2021-03-29 14:36 UTC, DunDung commented on build.gradle
> +}
war 추가한 이유를 알 수 있을까요??😮

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/UserSignupController.java
> +@RequestMapping("/api/signup")
아래 이미지 내용 읽어보세요!
![image](https://user-images.githubusercontent.com/33235211/112823119-d1ee2600-90c3-11eb-8412-9316b64c0e53.png)

*웹 API가 표시하는 비즈니스 엔터티에 집중해야 합니다. 예를 들어 전자 상거래 시스템에서는 기본 엔터티가 고객과 주문입니다.* 이 내용을 보시면 signup 이라는 리소스 URL은 비즈니스 엔터티에 집중했다고 보긴 어려울 것 같아요!
회원가입이라는 행위에 집중하기보다는 회원가입이 이루어지는 엔터티인 user에 집중해서
"/api/users" 가 맞다고 생각합니다!

 더 자세한 내용은 시간되실 때 [MS API 디자인 지침](https://docs.microsoft.com/ko-kr/azure/architecture/best-practices/api-design) 읽어보시면 좋을 듯!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/UserSignupController.java
> +    UserSignupService userSignupService;
DI를 @Autowired를 사용한 필드 주입으로 하셨는데 특별한 이유가 없다면
DI를 하는 3가지 방법을 공부해보시고 스프링 공식 레퍼런스에서는 왜 생성자 DI를 권장하는지 한 번 공부해보세요:)
공부하실 때 도움이 될만한 좋은 글 첨부합니다!
[왜 Constructor Injection을 사용해야 하는가?](https://woowacourse.github.io/javable/post/2020-07-18-di-constuctor-injection/)

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/UserSignupController.java
> +public class UserSignupController {
컨트롤러를 처음부터 너무 세분화하는 것은 좋지 않다고 생각합니다!
처음엔 UserController로 User 관련된 요청을 매핑해주는 Controller를 만들어주고
프로젝트를 진행하다가 UserController에서 너무 많은 요청을 받고 있는 듯한 느낌이 든다면
그 때 행위별로 책임과 역할을 분리해줘도 늦지 않다고 생각해요!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/UserSignupController.java
> +    @GetMapping("")
```suggestion
    @GetMapping
```
빈 문자열은 없어도 상관없습니다!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/UserSignupController.java
> +    public boolean checkEmail(@RequestBody String Email) {
컨트롤러에서 ResponseEntity 를 반환하는 것은 어떨까요?
ResponseEntity를 공부해보시고 ResponseEntity를 반환했을 때 어떤 장점이 있는지 공부해보아요!
[이 글](https://doublesprogramming.tistory.com/204)의 ResponseEntity 부분을 보면 도움이 될거예요 :)

또 사소한거지만 네이밍도 최대한 구체적으로 해주는 것이 좋다고 생각해요.
이메일 중복체크라면 isDuplicatedEmail 과 같이 어떤걸 check 해주는지 메서드 네이밍으로
의도를 확실히 표현해주는 것이 좋다고 생각합니다!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/UserSignupController.java
> +        return;
무의미한 return문은 없는것이 나을 수도 있슴니다!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/controller/UserSignupController.java
> +    public void userSignup(@RequestBody UserSignupDto userSignup) {
메서드 네임을 다시 한 번 고민해보아요!
메서드이름은 동사로 시작하는 것이 원칙입니다!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/dto/UserSignupDto.java
> +    private String nickname;
컨트롤러에서 요청을 받을 때 사용하는 DTO 같은데
관련해서 형준님 코드리뷰한 내용을 찾아보시고 공부하시면 좋을 것 같아요!
또 요청 받은 데이터를 검증하는 로직을 Spring validate를 사용해서 이 DTO에 추가해보아요!
Spring validation은 관련 좋은 글 첨부해드릴게요!
[Spring Boot에서 DTO 검증하기](https://woowacourse.github.io/javable/post/2020-09-20-validation-in-spring-boot/)

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/entity/User.java
> +@NoArgsConstructor
```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```

JPA에서 entity에는 기본 생성자가 꼭 필요하죠!
default는 아마.. public인데 많은 분들이 위에 추천 해드린것처럼 
access level을 protected로 제한하는데 왜 그런건지
공부해보시고 access level을 protected로 수정해보아요!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/entity/User.java
> +    @Column(nullable = false)
nullable = false로 설정해주면 정확히 어떻게 되는 걸까요!?
먼저 답을 생각해보시고 좋은 글 하나 추천해드립니다 👍 
[[JPA] nullable = false와 @NotNull의 차이점](https://bottom-to-top.tistory.com/14)

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/entity/User.java
> +
불필요한 공백은 가독성을 저해합니다! 코드 전체적으로 확인해주세영

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/mapper/UserMapper.java
> +public interface UserMapper {
저도 mapstruct를 써보진 않았지만
mapstruct를 쓸 때 장점, 단점을 생각, 찾아보시고 왜 썼는지를 답할 수 있어야해요!
장점이 단점보다 크다면 당연히 쓰는게 맞는거구요!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/mapper/UserMapper.java
> +    UserSignupDto userToUserSignupDto(User user);
위에 리뷰에서 말씀드렸듯이 네이밍은 다시 해야될 것 같아요 :)

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/service/UserSignupService.java
> +    UserMapper userMapper = UserMapper.INSTANCE;
우선 접근제한자는 private으로 걸어주는게 좋아보여요!  그리고
1. 상수로 사용
2. 메서드내에서만 사용

등의 선택지가 있어보여요. 인스턴스 변수로 가지고 있을 필요가 없어보입니다!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/entity/User.java
> +    private String nickname;
이메일 형식이나 닉네임 글자수, password 글자수나 형식 같은것을 검증해줄 필요가 있는 것 같아요!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/service/UserSignupService.java
> +    }
중복된 이메일이 있거나 패스워드가 불일치해서 회원가입을 실패했을 때의 처리도 있어야해요.
실패했을 때는 상황에 알맞은 exception과 메세지를 throw 하는 것이 어떨까요?
물론 이 부분도 테스트해줘야합니다!
그리고  exception을 처리하는 로직과 로그를 찍는 처리를 해줘야 해요.
`@RestControllerAdvice` 를 가지는 UserExceptionControllerAdivce 클래스를 하나 만들고
`@ExceptionHandler`를 통해 exception을 처리해줄 수 있어요.
물론 프론트에도 서버로부터 전달받은 예외를 처리하는 로직이 추가되어야하구요!

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/service/UserSignupService.java
> +    }
메서드 네임인 verifyEmail이 email의 뭘 검증하는지 의도가 명확히 표현되지 않는 것 같아요.
지금은 주석으로 부연 설명을 하고 있는데 메서드 네이밍을 잘하면 주석은 필요없습니다!
게다가 다른 곳에서 호출되는 이 메서드에도 전부 주석을 달아줄 순 없는거라 메서드 네이밍을 좀 더 고민해보아요!
아래 verifyPassword도 마찬가지입니다!

더해서 if문은 한줄이더라도 중괄호를 달아주는게 대부분 사용되는 컨벤션이에요.
컨벤션을 왜 지켜야 하는지는 [이 글](https://www.oracle.com/java/technologies/javase/codeconventions-introduction.html#16712)의 Why Have Code Conventions 부분을 꼭 읽어보세용!
[네이버 핵데이 코딩 컨벤션](https://naver.github.io/hackday-conventions-java/)을 가볍게 슥 읽어보며 파악해보시길 추천드립니다!

또 userRepository.findByEmail이 User를 바로 return하는데 이러면 verifyEmail처럼 findByEmail을 사용하는 모든 곳에서 null 체크를 해줘야하는데 누군가 실수하면 NullPointerException이 터질 가능성이 생기고
NPE가 터지면 서버가 종료되는 불상사가 발생할 수 있슴니다.
이런걸 방지하기 위해 repository에서부터  optional로 return하는게 좋습니다!
repository에서 optional로 리턴하도록 수정하고 이 메서드에서도 optional을 통해 로직을 처리해보면 좋을 것 같아요.

2021-03-29 14:36 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/service/UserSignupService.java
> +        String passwordCheck = userSignup.getPasswordCheck();
service에서 이 로직을 처리하기보다는 controller에서 DTO로 요청이 들어올 때 부터 검증을 해주는게 좋겠죠?!
위에서 말한 Spring validation을 사용하면 없어질 코드네요!

2021-03-29 14:36 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/mapper/UserMapperTest.java
> +public class UserMapperTest {
형준님과 마찬가지로 테스트 관련해서도 해드릴 말씀이 많지만!
이번에는 리뷰 내용이 많으니 수정 반영하시면 테스트는 그때 다시 리뷰해드릴게요!
처음이신데  👍

2021-04-06 11:14 UTC, DunDung requested changes
고생하셨습니다 신혁님 💯 
생각보다 저번 리뷰가 잘 반영되어있고
제 기준에선 저번보다 코드가 많이 좋아져서 놀랐어요!
이번 리뷰도 공부 열심히 해보시고
한 번더 코드 수정하시면 이제 테스트코드 꼼꼼히 봐드리겠습니다!

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controllerAdvice/UserExceptionControllerAdvice.java
> +@Slf4j
slf4j와 logback으로 로깅 👍👍👍

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controllerAdvice/UserExceptionControllerAdvice.java
> +        return new ResponseEntity("유효성 검증 실패", HttpStatus.BAD_REQUEST);
어떤 내용의 유효성 검증에 실패했는지 정확히 알려주어야 좋습니다!
프론트는 서버에서 온 이 에러 메세지를 받아서 사용자에게 보여줘야하는데
사용자 입장에서는 `유효성 검증 실패`만 딱 보이면 뭘 잘못 입력했는지 알 수가 없기때문입니다.
이 부분 뿐만 아니라 이렇게 에러 메세지를 보낼때는
 프론트에서 처리를 잘할 수 있고, 사용자가 쉽게 알아들을 수 있게 작성해주어야 좋습니다!
validation으로 검증할때
```java 
@Email(message = "이메일 형식이 맞지 않습니다.")
```
이런식으로 메세지를 구체적으로 보내고
```suggestion
    return ResponseEntity.badRequest().body(e.getMessage());
```
이렇게 처리해주면 될 것 같습니당.

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controller/UserController.java
> +        return new ResponseEntity("회원가입 성공", HttpStatus.OK);
POST 매핑으로 새로운 데이터를 저장했을 경우에는 200 OK도 가능하지만 
보통 201 created 상태 코드를 씁니다!
그리고 새로 생성 된 리소스를 반환받을 수 있는 uri를 header에 넣어줍니다!

응답한 데이터를 명확하게 표현하기 위한 ststus code 중에하나인 201 code도 공부해보길 추천해요!

userSignupService.save를 조금 수정하고 이런식으로 수정하면 될 거예요.
```suggestion
        return ResponseEntity.created(URI.create("/" + savedUser.getId())).build();
```

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controller/UserController.java
> +    public ResponseEntity<String> signup(@RequestBody @Valid UserSignupDto userSignupDto) {
메서드명 signUp이 맞지않나요?!? 저도 영어는 잘몰라서 ..,

uri는 수정할 필요가 있을 것 같아요. 비즈니스 엔터티에 집중해야하니까요!
그래서 uri는 그냥 users로  가는게 맞을 것 같아요. post mapping이라 그냥 users로 해도 의미전달이 명확합니다!
post mapping으로 "/users" 가  회원가입 의도를 전달하는데 왜 명확한지
 get, post 의 차이를 공부해보시길 추천해드려요!

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controller/UserController.java
> +    @GetMapping("/email")
uri가 get으로 /email인 경우에는 email 자체를 조회해온다는 식으로 생각할거예요.
명확하게 uri를 해주는 게 좋으니 "/emails/{email}/exists" 처럼 하는게 훨씬 좋아보입니다!

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/entity/UserEntity.java
> +    private int id;
Entity의 id는 보통 int를 사용하지 않고 널널한 long을 사용합니다!
몇 개의 entity가 db에 저장될 지 모르니까요!
그리고 primitive type 보다는 wrapper class를 사용합니다! 
그래서 Long을 사용하는게 적합하다고 볼 수 있어요.  왜일까요?!?

생각해보시고 [이 글](https://hanga-evernote.com/106)을 참고해보세요!
내용이 이해되지 않으시면 더 검색해보시길 추천드려요!

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controllerAdvice/UserExceptionControllerAdvice.java
> +        return new ResponseEntity("기타에러", HttpStatus.NOT_FOUND);
이 부분은 NOT_FOUND가 맞을까요!?? 아까 201 created를 공부하라고 말씀드렸던 것 처럼
이 부분에 적합한 status code는 뭘지 고민해보아요!

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/dto/UserSignupDto.java
> +        throw new SignupPasswordUnmatchedException("비밀번호 불일치");
네이밍이 isSamePassword 이면 리턴타입이 boolean으로 예상되고 당연히 if문 안에 있을 것 같은데
맨 윗줄에 덩그라니 있으니 조금 부자연스러워 보여요!
이런식으로 작성하는건 어떨까요!??
```suggestion
    public UserEntity toUserEntity() {
        validateSmaePassword(password, passwordCheck);
        UserEntity user = UserEntity.builder()
                .email(email)
                .password(password)
                .nickname(nickname)
                .build();
        return user;
    }

    public void validateSmaePassword(String password, String passwordCheck) {
        if (!password.equals(passwordCheck)) {
            throw new SignupPasswordUnmatchedException("비밀번호 불일치");
        }
    }
```
이런식으로 검증했을 것 같아요!
그리고 if문은 내용이 한 줄이라도 중괄호를 쳐주는게 주로 사용하는 컨벤션이더라구용.

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/exception/DuplicatedEmailException.java
> +}
custom exception 👍 👍  어떤 exception인지 더 명확하게 의도 전달이 가능할 것 같아요!

DuplicatedEmailExceptiop 같은 경우에는 RuntimeException을 상속받기 보다는
IllegalArgumentException 을 상속받는게 더 적합할 것 같아요!
각 Exception이 어떤 경우에 throw하는게 적합할지도 공부해보는게 좋겠네요!
그리고 NoArgsConstructor를 사용하는 경우가 없다면 굳이 안붙여도 돼요.

다른 customException도 검토해보시와용

2021-04-06 11:14 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/service/UserSignupService.java
> +}
중복된 이메일이라면 exception이 두 번 throw 하게 되있네요! 실제로는 DuplicatedEmailException만 터질거구요!
위 리뷰에도 말씀드렸듯이 검증을 하는 메서드라면 boolean타입으로 메서드를 작성할  필요가 없습니다!
void로 하고 네이밍도 더 명확하게 할 수 있구요! 
그리고 Eamil 중복여부를 검사할거라면 JPA exist를 사용하는게 더 좋아보여요!
repository에서 findByEmail처럼 existByEmail로 간단하게 만들 수 있습니다.
아래처럼 수정할 수 있을 것 같아요!
```suggestion
    @Transactional
    public UserEntity save(UserSignupDto userSignupDto) {
        validateDuplicatedEmail(userSignupDto.getEmail());
        UserEntity user = userSignupDto.toUserEntity();
        return userRepository.save(user);
    }

    public void validateDuplicatedEmail(String email) {
        if(userRepository.existsByEamil(email)) {
            throw new DuplicatedEmailException("중복된 이메일");
        }
    }
```

2021-04-06 11:43 UTC, rlatls1997 commented on src/main/java/com/skhu/luxuryshop/user/service/UserSignupService.java
> +}
리뷰 확인했습니다. 수정 후 다시 커밋해볼게요!

2021-04-12 05:59 UTC, DunDung requested changes
신혁님 고생하셨습니다 💯 
제 피드백 빠르게 흡수하고 계신 것 같아요!
테스트 코드도 처음하는 것 같지 않아요. 너무 잘하셨어요 👍 
제 리뷰가 정답이 아니니까 의문이 생기거나 더 맞는 방법이 있는 것 같으면 꼭 말해주세요.
이번 리뷰도 열심히 반영해보아요!!

2021-04-12 05:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controller/UserController.java
> +    @PostMapping()
```suggestion
    @PostMapping
```
이것도 가능함니다~~

2021-04-12 05:59 UTC, DunDung commented on build.gradle
> +}
이 부분은 답변이 없네요 ㅠㅠㅠ

2021-04-12 05:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controllerAdvice/UserExceptionControllerAdvice.java
> +    }
에러메시지를 꼼꼼히 작성하셨으니
methodArgumentNotValidException에서 처럼 통일하는건 어때요?
```java
 return ResponseEntity.badRequest().body(e.getMessage());
```

2021-04-12 05:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controllerAdvice/UserExceptionControllerAdvice.java
> +    }
지난번에 Exception에 적합한 status code를 찾아보라고 말씀드렸었는데 bad request를 선택하셨네요!
Exception은 가장 상위 타입이라 예상하지 못한 에러는 전부 이곳으로 핸들링 될거예요.
다시 말해서 사용자의 잘못된 요청에 의도적으로 던진 SignupPasswordUnmatchedException 같은 Exception이 아니라
예상하지 못한 서버 내부에서 발생하는 에러가 전부 이곳에 걸릴건데 
그게 사용자의 잘못된 요청때문이 아닐 가능성이 높아보여요.
그래서 이럴땐 500 Internal Server Error가 더 적합해 보입니다!
그리고 보안상의 이유로 예상치 못한 에러의 내용을 사용자에게 알려줄 필요는 없어요.
위의 핸들러메서드들 수정하시다가 이것도 수정하실까봐!
```java
ResponseEntity.badRequest().body(e.getMessage());
``` 
이렇게 수정하기보다 지금처럼 로그 찍고 예상치 못한 에러라고 알려주는 정도가 적합합니다~!
```java
ResponseEntity.badRequest().body("예상치 못한 에러.");
```

2021-04-12 05:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/dto/UserSignupDto.java
> +    //비밀번호 일치 불일치 검사
이제 주석은 없어도 의미전달이 됩니다!

2021-04-12 05:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/dto/UserSignupDto.java
> +        validateSamePassword(password, passwordCheck);
이렇게 toUserEntity 검증을 걸어줄지
롬복으로 걸어둔 All args 생성자를 직접 정의해주고
그 생성자 안에서 검증을 걸어줄지 한 번 고민해보세요!
정답은 없고 신혁님이 맞다고 생각하시는대로 가면 됩니다!!

2021-04-12 05:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/dto/UserSignupDto.java
> +    @NotNull(message = "비밀번호를 입력하세요.")
String에 `@NotNull`을 사용할 경우 null이 들어오는 것은 막을 수 있지만
`""` 처럼 빈 문자열이 들어오는 건 막을 수 없슴니다!
[이 글](https://dundung.tistory.com/271?category=761948) validator부분 참고해보세요!

2021-04-12 05:59 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/entity/UserEntity.java
> +public class UserEntity {
이 부분에는 왜 에러메세지가 없나요 ㅠㅠ
더 철저히 검증해줘야 하는 쪽은 이쪽입니다..

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/controller/UserControllerTest.java
> +    UserSignupService userSignupService;
테스트 코드도 유지보수가 필요한 코드이고 
테스트들간의 독립성이 보장되어야해요! 그래서 별건아니지만 
인스턴스변수에도 private를 붙여주는게 어떤가요?!

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/controller/UserControllerTest.java
> +    }
`BeforeEach`를 붙인 메서드는 setUp으로 메서드명을 지어주는게 컨벤션 일거예요.
자동생성해도 setUp으로 이름이 지어지구요!
그리고 BeforeEach 어노테이션을 붙인 이 setUp메서드는 해당 클래스에서
테스트 메서드 하나씩 실행하기 전마다 실행되기 전마다 실행되는데 알고계셨나요!?
이 클래스에서는 테스트 메서드가 2개니까 2번 실행되겠네요!
그래서 두 곳의 테스트메서드에서 사용되는 애들만 코드 중복을 줄이기 위해서 setUp메서드에서 초기화해주는게
좋습니다! 인스턴스 변수도 마찬가지로 지금 너무 많아요. 2 곳에서 전부 사용되는 변수가 아니라면
해당 메서드에서 생성하는 게 조아보여요!

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/controller/UserControllerTest.java
> +    void test_isDuplicatedEmail() throws Exception {
테스트 코드에서도 메서드이름으로 어떤 경우를 테스트하는지를 보여줘야하는데
그걸 영어로 일일이 고민하면 너무 힘들잖아요?!?
그래서 `@DisplayName`을 많이 애용합니다.
메서드명은 대충 짓고 DisplayName에 한글로 어떠한 경우를 테스트하는지 명확하게 작성해보아요.
`@DisplayName("이메일 중복 요청인 경우 BadRequest")`

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/controller/UserControllerTest.java
> +                .andDo(print());
하나의 테스트에는 하나의  case 만 테스트하는 것이 맞습니다!
실제 현업의 프로젝트에 무수히 많은 테스트 코드가 있다고 가정할 때
테스트 코드가 많이 실패한 경우 어떤 case가 실패했는지 한눈에 알아야해요.
위 코드 같은 경우엔 2가지 경우를 한 메서드에서 테스트하고 있어서
이 테스트 메서드가 깨져도 어떤 경우가 실패한건지 한 번에 알 수 없습니다!

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/controller/UserControllerTest.java
> +    }
👍  처음 하신 거 맞나요?!!?? 최고입니다.
다만 헤더에 들어가는 리소스 위치 검증도 추가해주세요!
내가 작성한 코드로 나오는 결과는 전부 검증해주는게 원칙임니당.😊

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/dto/UserResponseDtoTest.java
> +@SpringBootTest
UserResponseDto 테스트에 SpringBootTest가 필요할까요!?
`@SpringBootTest`가 머하는 어노테이션인지 한 번 더 검색해보아요!
얘가 굉장히 느려서 꼭 필요한 테스트클래스에만 붙여주어야 해요. 
`@SpringBootTest` 검색해보시고 이 테스트클래스 이외 클래스들도 붙일 필요가 있는지 검토해보세요~~

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/dto/UserResponseDtoTest.java
> +        assertEquals(user.getNickname(), userResponseDto.getNickname());
junit5로 검증하는 것도 좋지만
AssertJ를 사용하시는 분과 기업이 훨씬 많을거예요!
AssertJ로 test하면 훨씬 명확하고 좋습니다! 기능도 훨씬 더 많구요!
junit이랑 사용법이 비슷해서 금방 배우실 거예용

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/service/UserSignUpServiceTest.java
> +    //회원생성 테스트
항상 주석을 다시기전에 어떻게하면 주석을 안 달수있을까를 고민해보세요!
여기에서는 제가 위에서 말한 DisplayName을 사용하면 안 붙일 수 있겠네요 :)

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/service/UserSignUpServiceTest.java
> +            userSignupService.save(unmatchedPwdUserSignup);
여기서도 2개의 case를 한 메서드에서 test하고 있군요!

2021-04-12 05:59 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/service/UserSignUpServiceTest.java
> +    }
이 메서드가 꼭 필요한지 고민할 필요가 있습니다:)
테스트를 할때는 대부분 h2 같은걸로 테스트 디비를 따로 두고
해당 테스트 클래스에서 생성되는 것들만 디비에 저장 되어있기 때문에
중복된 이메일, 중복되지 않은 이메일을 충분히 쉽게 제어 가능합니다!=

2021-04-22 14:07 UTC, DunDung approved these changes
신혁님 리뷰 반영 완전 잘하셨어요.💯
war 추가한 이유만 말씀해주시고 무슨 문제있으면 같이 해결해봐요. 그리고나서  merge 하면 될 것 같아요! 
리뷰한 보람을 느끼네요 굿굿

2021-04-22 14:07 UTC, DunDung commented on build.gradle
> +}
이 부분은 들을 수 없는건가요 ㅠㅠ

2021-04-22 14:07 UTC, DunDung commented on build.gradle
> +    testCompile("org.assertj:assertj-core:3.11.1")
이거는 추가 안해도되는 걸로 알고있어요
spring-boot-starter-test에 포함되어 있을 거예요
```suggestion
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
```
이렇게 수정해 보실래요!?

2021-04-22 14:07 UTC, DunDung commented on src/frontend/src/api/index.js
> +};
```suggestion
const config = {
    baseUrl: '/api/users/'
};
```
이렇게 하시면 CORS 문제 안생길거예요.
vue config에 proxy 설정을 해둬서 자동으로 8080으로 갑니다!

2021-04-22 14:07 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/controller/UserController.java
> +@CrossOrigin(origins = {"http://localhost:9000"})
위에 리뷰 달아드린 base url 수정하시고 이부분 제거해보세요!

2021-04-23 06:27 UTC, rlatls1997 commented on src/test/java/com/skhu/luxuryshop/user/controller/UserControllerTest.java
> +}
이 부분 테스트에서
비밀번호불일치 유저와 이메일이 중복된 유저에 대한 테스트가 빠졌는데

userSignupService.save에서 ArgumentMatchers.any()로 지정하는 법 말고
content로 들어가는 그 유저에 대한 메소드가 불렸을 때를
어떻게 설정해야 하는지 모르겠어서 일단 정상유저에 대한 테스트만 했습니다!

2021-04-23 06:27 UTC, rlatls1997 commented on build.gradle
> +}
답변이 늦었네요 ㅠ 이 부분은 저번 aws배포할 때 war생성하면서 사용했던 코드입니다!

2021-04-23 06:27 UTC, rlatls1997 commented on src/main/java/com/skhu/luxuryshop/user/dto/UserSignupDto.java
> +        validateSamePassword(password, passwordCheck);
잘 모르겠어서 질문드립니다..

all args생성자 안에 검증을 추천해주신이유가 
비밀번호가 일치하지 않는 객체의 생성 자체를 막기 위해서인가요?
아니면 다른 이유가 있나요??

2021-04-23 06:39 UTC, DunDung commented on src/test/java/com/skhu/luxuryshop/user/controller/UserControllerTest.java
> +}
```java
given(userSignupService.save(any()))
                .thenThrow(CustomException);
```
thenReturn을 사용하신 것 처럼 thenThrow를 사용해서
요런식으로 해당 메서드에서 throw를 발생시키게 설정해주고
적합한 HttpStatus가 return되는지 확인하는 테스트를 작성하시면 됩니다!

2021-04-23 06:42 UTC, DunDung commented on build.gradle
> +}
프로젝트에 설정된 jar로 aws 배포가 가능합니다!

2021-04-23 06:45 UTC, DunDung commented on src/main/java/com/skhu/luxuryshop/user/dto/UserSignupDto.java
> +        validateSamePassword(password, passwordCheck);
생성 자체를 막아서 검증되지 않은 불안전한 객체가 이리저리 호출되는 것을 처음부터 막으면
더 안전한 프로그램이 되겠죠! 도메인 객체는 항상 안전해야 합니다! 그래서 불변 객체로 만들기도 하구요.
정답은 없고 생각하기 나름입니다!

2021-04-23 12:21 UTC, jhj960918 commented
확인 했습니다

2021-04-23 12:22 UTC, jhj960918 approved these changes
확인 했습니다.

2021-04-24 12:13 UTC, merged